#!/bin/bash

CC=$(which gcc)
CFLAGS+="-g -std=c11 -pedantic -Wall $(sdl2-config --cflags)"

LD=$(which gcc)
LFLAGS="$(sdl2-config --libs) -lSDL2main -lGL -lGLEW"

VERSION=gnu11

if [ ! -d output ]; then
    mkdir -p output
fi

rm -rf output/*.o

OBJS=""
SRCS=(\
       opcode \
       system \
       input \
       main \
)
for SRC in "${SRCS[@]}"; do
    $CC $CFLAGS -c $SRC.c -o output/$SRC.o
    OBJS+=" output/$SRC.o"
done

CMD="$CC -o output/chip-8 $OBJS $LFLAGS"
echo "$CMD"
$CMD
