#!/bin/sh

VERSION=gnu11

rm -rf *.o
gcc -g -std=$VERSION -c opcode.c
gcc -g -std=$VERSION -c system.c
gcc -g -std=$VERSION -c gs_stack.c
gcc -g -std=$VERSION -c main.c
gcc -g -std=$VERSION -o chip-8 gs_stack.o system.o opcode.o main.o
